
###
###
POST http://localhost:80/sync-drivers

###
###
GET http://localhost:5041/drivers





###
###
POST http://localhost:80/sync-drivers-results

###
###
GET http://localhost:5041/drivers/hamilton/results






###
###
POST http://localhost:80/sync-calendar


###
###
GET http://localhost:80/calendar